     C                   z-add     10001161      UUNIK             9 0
     C                   z-add     0             UFBNR             3 0
     C                   z-add     3             ULINR             2 0
     C                   call      'SYGE85Z'
     C                   PARM                    UUNIK             9 0
     C                   PARM                    UFBNR             3 0
     C                   PARM                    ULINR             2 0
     c                   seton                                        LR
     C                   return
