      *
     C                   z-add     0001          UUAVD             4 0
     C                   z-add     0155498       UUOPD             7 0
     C                   CALL      'SYFA10T'
     C                   PARM                    UUAVD             4 0
     C                   PARM                    UUOPD             7 0
     C                   seton                                        LR
